/**
 * Единая точка констант баланса фаз 1–2 (поле, спавн, улучшения дыры).
 * Источник истины по формулам: obsidian/07; темп и ручки — obsidian/13.
 */

export {
  BASE_SPAWN_PER_SECOND,
  MAX_OBJECTS_ON_FIELD,
  SHIP_SPAWN_FRACTION,
  SPAWN_WEIGHTS,
} from "./spawn";

export type { ObjectKind } from "./objectKinds";
export { MP_RANGE, OBJECT_MASS } from "./objectKinds";

export {
  SHIPS_UNLOCK_MIN_SUM,
  SUM_FOR_DISK_UNLOCK,
  SUM_FOR_EFFICIENCY_UNLOCK,
  SUM_FOR_HAWKING_UNLOCK,
  SUM_FOR_JETS_UNLOCK,
  SUM_FOR_LENSING_UNLOCK,
  VIEW_TIER_GALAXY_MIN_SUM,
  VIEW_TIER_SYSTEM_MIN_SUM,
} from "./unlocks";

export {
  HAWKING_BASE_MP_PER_SEC,
  HAWKING_MASS_LOG_COEFF,
  HAWKING_PER_LEVEL_FACTOR,
  JET_BASE_PROC_CHANCE,
  JET_BUFF_DURATION_SEC,
  JET_FIELD_MP_MULT,
  JET_IMPULSE_SPEED,
  JET_PROC_ATTEMPT_INTERVAL_SEC,
  JET_PROC_CHANCE_PER_LEVEL,
  LENSING_RARE_WEIGHT_MULT_PER_LEVEL,
} from "./branchA46";

export {
  SHIP_THRUST_DISK_FACTOR_PER_LEVEL,
  SHIP_THRUST_EFFICIENCY_FACTOR_PER_LEVEL,
  UPGRADE_COST_MULTIPLIER_PER_LEVEL,
  UPGRADE_FIRST_LEVEL_COST_MP,
  UPGRADE_PER_LEVEL_FACTOR,
} from "./upgradeEconomy";

export {
  BASE_GRAVITY_FRACTION,
  BASE_HORIZON_FRACTION,
  BH_ORBIT_RADIUS_FRACTION,
  BH_SCREEN_ANGLE_RAD,
  CAMERA_SCALE_MIN,
  STAR_COLLISION_RADIUS_FRACTION,
  STAR_DISPLAY_RADIUS_FRACTION,
  STELLAR_SYSTEM_RADIUS_MUL,
  SYSTEM_OUTER_RADIUS_FRACTION,
  USER_ZOOM_MAX,
  USER_ZOOM_MIN,
  VIEW_TIER_SYSTEM_SCALE_MUL,
} from "./layoutViewport";

export {
  BASE_GRAVITY_ACCEL,
  BASE_BH_MASS,
  BASE_STAR_MASS,
  GRAVITY_CONST,
  GRAVITY_FIELD_BLEND_IN_FRAC,
  GRAVITY_FIELD_BLEND_OUT_FRAC,
  GRAVITY_RADIUS_MIN_OVER_HORIZON,
  GRAVITY_SOFTENING,
  OUTSIDE_GRAVITY_RATIO,
  SHIP_THRUST_BASE,
  VELOCITY_DAMPING,
} from "./simulationPhysics";

export {
  FIELD_MP_GLOBAL_MULTIPLIER,
  INCOME_SOFTCAP,
  softCapIncomeMul,
} from "./economyTuning";

export {
  PLANET_ACCELERATION_BASE_MP,
  PLANET_ACCELERATION_MULTIPLIER_MAX,
  PLANET_ACCELERATION_SECONDS,
  PLANET_ECOSYSTEM_HIGH,
  PLANET_ECOSYSTEM_LOW,
  PLANET_GOLDEN_MID,
  PLANET_LIFE_EMERGENCE_TOTAL_SEC,
  PLANET_CIV_STAGE_SEC,
  PLANET_CIV_MAX_LEVEL,
  PLANET_TRIBUTE_INTERVAL_SEC,
  PLANET_TERRAFORM_STEP,
  PLANET_TERRAFORM_COST_MP,
  PLANET_SHIELD_DURATION_SEC,
  PLANET_SHIELD_COST_MP,
  PLANET_STAGE_DURATIONS_MIN,
  PLANET_STAGE_DURATIONS_SEC,
  PLANETS_FIRST_SYSTEM_MAX,
  PLANETS_FIRST_SYSTEM_MIN,
  PLANETS_PER_SYSTEM_MAX,
  PLANETS_PER_SYSTEM_MIN,
  PLANET_SYSTEM_COUNT_MAX,
  PLANET_SYSTEM_COUNT_MIN,
} from "./planetTuning";
